/**
 * Export Utilities — EGOS Inteligência
 * Sacred Code: 000.111.369.963.1618 (∞△⚡◎φ)
 * 
 * PDF, CSV, JSON export functionality
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ExportOptions {
  format: 'pdf' | 'csv' | 'json' | 'md';
  filename?: string;
  title?: string;
  includeMetadata?: boolean;
}

// Export investigation to PDF
export async function exportToPDF(
  data: {
    title: string;
    description?: string;
    entities: any[];
    relationships: any[];
    timeline?: any[];
  },
  options: ExportOptions
): Promise<Blob> {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text(data.title, 14, 20);
  
  // Description
  if (data.description) {
    doc.setFontSize(12);
    doc.text(data.description, 14, 30);
  }
  
  // Entities table
  if (data.entities.length > 0) {
    doc.setFontSize(14);
    doc.text('Entities', 14, 45);
    
    autoTable(doc, {
      startY: 50,
      head: [['ID', 'Type', 'Name', 'Properties']],
      body: data.entities.map(e => [
        e.id,
        e.labels?.[0] || 'Unknown',
        e.properties?.name || 'N/A',
        Object.entries(e.properties || {})
          .slice(0, 3)
          .map(([k, v]) => `${k}: ${v}`)
          .join(', '),
      ]),
    });
  }
  
  // Relationships table
  if (data.relationships.length > 0) {
    const finalY = (doc as any).lastAutoTable?.finalY || 70;
    doc.setFontSize(14);
    doc.text('Relationships', 14, finalY + 15);
    
    autoTable(doc, {
      startY: finalY + 20,
      head: [['From', 'Type', 'To', 'Properties']],
      body: data.relationships.map((r: any) => [
        r.startNode,
        r.type,
        r.endNode,
        Object.entries(r.properties || {})
          .slice(0, 2)
          .map(([k, v]) => `${k}: ${v}`)
          .join(', '),
      ]),
    });
  }
  
  // Footer
  doc.setFontSize(10);
  doc.text(
    `Generated by EGOS Inteligência — ${new Date().toLocaleString()}`,
    14,
    doc.internal.pageSize.height - 10
  );
  
  return doc.output('blob');
}

// Export to CSV
export function exportToCSV(
  data: any[],
  options: ExportOptions
): Blob {
  if (data.length === 0) {
    return new Blob([''], { type: 'text/csv' });
  }
  
  // Get headers from first object
  const headers = Object.keys(data[0]);
  
  // Create CSV content
  const csvContent = [
    headers.join(','),
    ...data.map(row =>
      headers
        .map(header => {
          const value = row[header];
          // Escape values with commas or quotes
          if (
            typeof value === 'string' &&
            (value.includes(',') || value.includes('"') || value.includes('\n'))
          ) {
            return `"${value.replace(/"/g, '""')}"`;
          }
          return value ?? '';
        })
        .join(',')
    ),
  ].join('\n');
  
  return new Blob([csvContent], { type: 'text/csv' });
}

// Export to JSON
export function exportToJSON(
  data: any,
  options: ExportOptions
): Blob {
  const jsonContent = JSON.stringify(data, null, 2);
  return new Blob([jsonContent], { type: 'application/json' });
}

// Export to Markdown
export function exportToMarkdown(
  data: {
    title: string;
    description?: string;
    entities: any[];
    relationships: any[];
    findings?: string[];
  },
  options: ExportOptions
): Blob {
  let md = `# ${data.title}\n\n`;
  
  if (data.description) {
    md += `${data.description}\n\n`;
  }
  
  // Entities section
  md += `## Entities (${data.entities.length})\n\n`;
  for (const entity of data.entities) {
    md += `### ${entity.properties?.name || entity.id}\n\n`;
    md += `- **ID:** ${entity.id}\n`;
    md += `- **Type:** ${entity.labels?.join(', ') || 'Unknown'}\n`;
    md += `- **Properties:**\n`;
    for (const [key, value] of Object.entries(entity.properties || {})) {
      md += `  - ${key}: ${value}\n`;
    }
    md += '\n';
  }
  
  // Relationships section
  md += `## Relationships (${data.relationships.length})\n\n`;
  md += '| From | Type | To |\n';
  md += '|------|------|-----|\n';
  for (const rel of data.relationships) {
    md += `| ${rel.startNode} | ${rel.type} | ${rel.endNode} |\n`;
  }
  md += '\n';
  
  // Findings section
  if (data.findings && data.findings.length > 0) {
    md += `## Findings\n\n`;
    for (const finding of data.findings) {
      md += `- ${finding}\n`;
    }
    md += '\n';
  }
  
  // Footer
  md += `---\n\n`;
  md += `*Generated by EGOS Inteligência — ${new Date().toLocaleString()}*\n`;
  
  return new Blob([md], { type: 'text/markdown' });
}

// Download blob as file
export function downloadBlob(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
}

// Main export function
export async function exportData(
  data: any,
  options: ExportOptions
): Promise<void> {
  const filename = options.filename || `export-${Date.now()}`;
  
  switch (options.format) {
    case 'pdf':
      const pdfBlob = await exportToPDF(data, options);
      downloadBlob(pdfBlob, `${filename}.pdf`);
      break;
    case 'csv':
      const csvBlob = exportToCSV(data, options);
      downloadBlob(csvBlob, `${filename}.csv`);
      break;
    case 'json':
      const jsonBlob = exportToJSON(data, options);
      downloadBlob(jsonBlob, `${filename}.json`);
      break;
    case 'md':
      const mdBlob = exportToMarkdown(data, options);
      downloadBlob(mdBlob, `${filename}.md`);
      break;
    default:
      throw new Error(`Unsupported format: ${options.format}`);
  }
}

export default {
  exportToPDF,
  exportToCSV,
  exportToJSON,
  exportToMarkdown,
  exportData,
  downloadBlob,
};
